repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.18.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
